export type ElementalType =
  | "normal"
  | "feu"
  | "eau"
  | "plante"
  | "electrique"
  | "glace"
  | "combat"
  | "poison"
  | "sol"
  | "vol"
  | "psy"
  | "insecte"
  | "roche"
  | "spectre"
  | "dragon"
  | "tenebres"
  | "acier"
  | "fee";

export const ELEMENTAL_TYPES: ElementalType[] = [
  "normal",
  "feu",
  "eau",
  "plante",
  "electrique",
  "glace",
  "combat",
  "poison",
  "sol",
  "vol",
  "psy",
  "insecte",
  "roche",
  "spectre",
  "dragon",
  "tenebres",
  "acier",
  "fee",
];

export interface SpeciesConfig {
  key: string;
  name: string;
  /** Real national Pokédex number, for the Pokédex-style collection UI. */
  dexNumber: number;
  /** 1 or 2 types, matching the species' real in-game typing exactly. */
  types: ElementalType[];
  baseAttack: number;
  baseHp: number;
  baseCaptureRate: number;
  rarityWeight: number;
  /** Filename under /sprites/ in the web app's public assets. */
  spriteFile: string;
  /** Relative on-screen size, derived from the species' real height (PokeAPI, dampened via
   * sqrt-ish compression + clamped to [0.55, 1.15] so nothing vanishes or blows out a fixed
   * sprite box) — applied as a CSS transform: scale() on top of the existing object-contain
   * box everywhere a creature sprite renders (see creatureSpriteScale in theme/typeColors.ts).
   * Guarantees a species' own evolution family renders in ascending size order (e.g. Kaiminus
   * < Crocrodil < Aligatueur), which raw sprite pixel dimensions alone don't guarantee since
   * every sprite is pre-cropped tight to its own content (see the sprite-padding fix). */
  spriteScale: number;
  /** Only present for species with a real *level-based* evolution in the actual games —
   * stone/friendship/trade evolutions (Eevee, Vulpix, Growlithe, Pikachu, Buneary, Budew,
   * Cottonee, Sunkern, Staryu...) are deliberately omitted since they have no real level to
   * copy, per the "exact same level as the real game" requirement. `level` is the level at
   * which the creature auto-evolves into `intoKey`. */
  evolution?: { intoKey: string; level: number };
  /** Real stone-triggered evolutions (the ones `evolution` above deliberately excludes) —
   * player-initiated via a Pierre from the shop, not automatic. A species can have several
   * options (Eevee has 4: Fire/Water/Thunder/Leaf), each keyed by which stone unlocks it.
   * See STONE_CATALOG (game/stones.ts) and resolveStoneEvolution (game/evolution.ts). */
  stoneEvolutions?: { stoneKey: string; intoKey: string }[];
}

/** Offered to a new player on first login; a classic feu/eau/plante trio. */
export const STARTER_SPECIES_KEYS = ["salamandre", "grenouille", "lierre"] as const;

export const SPECIES_CATALOG: Record<string, SpeciesConfig> = {
  moineau: {
    key: "moineau",
    name: "Roucool",
    dexNumber: 16,
    types: ["normal", "vol"],
    baseAttack: 8,
    baseHp: 30,
    baseCaptureRate: 0.5,
    rarityWeight: 50,
    spriteFile: "pidgey.png",
    spriteScale: 0.75,
    evolution: { intoKey: "pidgeotto", level: 18 },
  },
  pidgeotto: {
    key: "pidgeotto",
    name: "Roucoups",
    dexNumber: 17,
    types: ["normal", "vol"],
    // Growth rates below (this chain and every other evolved-form entry in this file) are
    // derived from real per-stage stat ratios (PokeAPI attack/hp), applied on top of each
    // family's own hand-tuned base-form stats — not an invented flat multiplier. The original
    // flat ~1.5x/1.4x compounding made fully-evolved (3-stage) Pokémon noticeably overtuned
    // (~2.1x attack base-to-final) compared to how the real games actually pace evolution
    // power — see [[project-farmclicker-architecture-decisions]] for the rebalance note.
    baseAttack: 11,
    baseHp: 47,
    baseCaptureRate: 0.3,
    rarityWeight: 1,
    spriteFile: "pidgeotto.png",
    spriteScale: 0.87,
    evolution: { intoKey: "pidgeot", level: 36 },
  },
  pidgeot: {
    key: "pidgeot",
    name: "Roucarnage",
    dexNumber: 18,
    types: ["normal", "vol"],
    baseAttack: 15,
    baseHp: 62,
    baseCaptureRate: 0.18,
    rarityWeight: 1,
    spriteFile: "pidgeot.png",
    spriteScale: 0.91,
  },
  ecureuil: {
    key: "ecureuil",
    name: "Fouinette",
    dexNumber: 161,
    types: ["normal"],
    baseAttack: 9,
    baseHp: 26,
    baseCaptureRate: 0.45,
    rarityWeight: 40,
    spriteFile: "sentret.png",
    spriteScale: 0.84,
    evolution: { intoKey: "furret", level: 15 },
  },
  salamandre: {
    key: "salamandre",
    name: "Salamèche",
    dexNumber: 4,
    types: ["feu"],
    baseAttack: 12,
    baseHp: 28,
    baseCaptureRate: 0.35,
    rarityWeight: 30,
    spriteFile: "charmander.png",
    spriteScale: 0.81,
    evolution: { intoKey: "charmeleon", level: 16 },
  },
  charmeleon: {
    key: "charmeleon",
    name: "Reptincel",
    dexNumber: 5,
    types: ["feu"],
    baseAttack: 15,
    baseHp: 42,
    baseCaptureRate: 0.21,
    rarityWeight: 1,
    spriteFile: "charmeleon.png",
    spriteScale: 0.87,
    evolution: { intoKey: "charizard", level: 36 },
  },
  charizard: {
    key: "charizard",
    name: "Dracaufeu",
    dexNumber: 6,
    types: ["feu", "vol"],
    baseAttack: 20,
    baseHp: 56,
    baseCaptureRate: 0.13,
    rarityWeight: 1,
    spriteFile: "charizard.png",
    spriteScale: 0.93,
  },
  renardeau: {
    key: "renardeau",
    name: "Goupix",
    dexNumber: 37,
    types: ["feu"],
    baseAttack: 14,
    baseHp: 24,
    baseCaptureRate: 0.3,
    rarityWeight: 20,
    spriteFile: "vulpix.png",
    spriteScale: 0.81,
    stoneEvolutions: [{ stoneKey: "pierre_feu", intoKey: "ninetales" }],
  },
  ninetales: {
    key: "ninetales",
    name: "Feunard",
    dexNumber: 38,
    types: ["feu"],
    baseAttack: 21,
    baseHp: 30,
    baseCaptureRate: 0.18,
    rarityWeight: 1,
    spriteFile: "ninetales.png",
    spriteScale: 0.87,
  },
  loutre: {
    key: "loutre",
    name: "Moustillon",
    dexNumber: 501,
    types: ["eau"],
    baseAttack: 11,
    baseHp: 30,
    baseCaptureRate: 0.4,
    rarityWeight: 30,
    spriteFile: "oshawott.png",
    spriteScale: 0.79,
    evolution: { intoKey: "dewott", level: 17 },
  },
  dewott: {
    key: "dewott",
    name: "Mateloutre",
    dexNumber: 502,
    types: ["eau"],
    baseAttack: 15,
    baseHp: 41,
    baseCaptureRate: 0.24,
    rarityWeight: 1,
    spriteFile: "dewott.png",
    spriteScale: 0.84,
    evolution: { intoKey: "samurott", level: 36 },
  },
  samurott: {
    key: "samurott",
    name: "Clamiral",
    dexNumber: 503,
    types: ["eau"],
    baseAttack: 20,
    baseHp: 52,
    baseCaptureRate: 0.14,
    rarityWeight: 1,
    spriteFile: "samurott.png",
    spriteScale: 0.91,
  },
  grenouille: {
    key: "grenouille",
    name: "Grenousse",
    dexNumber: 656,
    types: ["eau"],
    baseAttack: 10,
    baseHp: 32,
    baseCaptureRate: 0.42,
    rarityWeight: 35,
    spriteFile: "froakie.png",
    spriteScale: 0.75,
    evolution: { intoKey: "frogadier", level: 16 },
  },
  frogadier: {
    key: "frogadier",
    name: "Croâporal",
    dexNumber: 657,
    types: ["eau"],
    baseAttack: 11,
    baseHp: 42,
    baseCaptureRate: 0.25,
    rarityWeight: 1,
    spriteFile: "frogadier.png",
    spriteScale: 0.81,
    evolution: { intoKey: "greninja", level: 36 },
  },
  greninja: {
    key: "greninja",
    name: "Amphinobi",
    dexNumber: 658,
    types: ["eau", "tenebres"],
    baseAttack: 17,
    baseHp: 56,
    baseCaptureRate: 0.15,
    rarityWeight: 1,
    spriteFile: "greninja.png",
    spriteScale: 0.91,
  },
  lierre: {
    key: "lierre",
    name: "Mystherbe",
    dexNumber: 43,
    types: ["plante", "poison"],
    baseAttack: 9,
    baseHp: 34,
    baseCaptureRate: 0.45,
    rarityWeight: 35,
    spriteFile: "oddish.png",
    spriteScale: 0.79,
    evolution: { intoKey: "gloom", level: 21 },
  },
  gloom: {
    key: "gloom",
    name: "Ortide",
    dexNumber: 44,
    types: ["plante", "poison"],
    baseAttack: 14,
    baseHp: 43,
    baseCaptureRate: 0.27,
    rarityWeight: 1,
    spriteFile: "gloom.png",
    spriteScale: 0.84,
    stoneEvolutions: [
      { stoneKey: "pierre_feuille", intoKey: "vileplume" },
      { stoneKey: "pierre_soleil", intoKey: "bellossom" },
    ],
  },
  vileplume: {
    key: "vileplume",
    name: "Rafflesia",
    dexNumber: 45,
    types: ["plante", "poison"],
    baseAttack: 20,
    baseHp: 52,
    baseCaptureRate: 0.16,
    rarityWeight: 1,
    spriteFile: "vileplume.png",
    spriteScale: 0.88,
  },
  bellossom: {
    key: "bellossom",
    name: "Joliflor",
    dexNumber: 182,
    types: ["plante"],
    baseAttack: 18,
    baseHp: 50,
    baseCaptureRate: 0.17,
    rarityWeight: 1,
    spriteFile: "bellossom.png",
    spriteScale: 0.84,
  },
  scarabee: {
    key: "scarabee",
    name: "Larveyette",
    dexNumber: 540,
    types: ["insecte", "plante"],
    baseAttack: 13,
    baseHp: 26,
    baseCaptureRate: 0.32,
    rarityWeight: 22,
    spriteFile: "sewaddle.png",
    spriteScale: 0.75,
    evolution: { intoKey: "swadloon", level: 20 },
  },
  swadloon: {
    key: "swadloon",
    name: "Couverdure",
    dexNumber: 541,
    types: ["insecte", "plante"],
    baseAttack: 20,
    baseHp: 33,
    baseCaptureRate: 0.19,
    rarityWeight: 1,
    spriteFile: "swadloon.png",
    spriteScale: 0.79,
  },
  "moucheron-foudre": {
    key: "moucheron-foudre",
    name: "Statitik",
    dexNumber: 595,
    types: ["insecte", "electrique"],
    baseAttack: 16,
    baseHp: 20,
    baseCaptureRate: 0.25,
    rarityWeight: 12,
    spriteFile: "joltik.png",
    spriteScale: 0.69,
    evolution: { intoKey: "galvantula", level: 36 },
  },
  galvantula: {
    key: "galvantula",
    name: "Mygavolt",
    dexNumber: 596,
    types: ["insecte", "electrique"],
    baseAttack: 24,
    baseHp: 25,
    baseCaptureRate: 0.15,
    rarityWeight: 1,
    spriteFile: "galvantula.png",
    spriteScale: 0.84,
  },
  "goupil-etincelle": {
    key: "goupil-etincelle",
    name: "Dynavolt",
    dexNumber: 309,
    types: ["electrique"],
    baseAttack: 18,
    baseHp: 22,
    baseCaptureRate: 0.2,
    rarityWeight: 8,
    spriteFile: "electrike.png",
    spriteScale: 0.81,
    evolution: { intoKey: "manectric", level: 26 },
  },
  manectric: {
    key: "manectric",
    name: "Élecsprint",
    dexNumber: 310,
    types: ["electrique"],
    baseAttack: 27,
    baseHp: 28,
    baseCaptureRate: 0.12,
    rarityWeight: 1,
    spriteFile: "manectric.png",
    spriteScale: 0.91,
  },
  mew: {
    key: "mew",
    name: "Mew",
    dexNumber: 151,
    types: ["psy"],
    // Nerfed 20% from the original 25/50 — it fights at level 30 (see lumina.ts) while the
    // rest of Route 3 is level 6-9, so its combat stats needed to come down to compensate.
    baseAttack: 20,
    baseHp: 40,
    baseCaptureRate: 0.03,
    rarityWeight: 1,
    spriteFile: "mew.png",
    spriteScale: 0.78,
  },

  // --- Route 1 (normal, low tier) ---
  rattata: { key: "rattata", name: "Rattata", dexNumber: 19, types: ["normal"], baseAttack: 7, baseHp: 22, baseCaptureRate: 0.55, rarityWeight: 40, spriteFile: "rattata.png", spriteScale: 0.75, evolution: { intoKey: "raticate", level: 20 } },
  zigzagoon: { key: "zigzagoon", name: "Zigzaton", dexNumber: 263, types: ["normal"], baseAttack: 8, baseHp: 24, baseCaptureRate: 0.5, rarityWeight: 32, spriteFile: "zigzagoon.png", spriteScale: 0.78, evolution: { intoKey: "linoone", level: 20 } },
  bidoof: { key: "bidoof", name: "Keunotor", dexNumber: 399, types: ["normal"], baseAttack: 6, baseHp: 28, baseCaptureRate: 0.55, rarityWeight: 28, spriteFile: "bidoof.png", spriteScale: 0.79, evolution: { intoKey: "bibarel", level: 15 } },
  bibarel: { key: "bibarel", name: "Castorno", dexNumber: 400, types: ["normal", "eau"], baseAttack: 9, baseHp: 35, baseCaptureRate: 0.33, rarityWeight: 1, spriteFile: "bibarel.png", spriteScale: 0.86 },
  lillipup: { key: "lillipup", name: "Ponchiot", dexNumber: 506, types: ["normal"], baseAttack: 9, baseHp: 24, baseCaptureRate: 0.5, rarityWeight: 20, spriteFile: "lillipup.png", spriteScale: 0.78, evolution: { intoKey: "herdier", level: 16 } },
  herdier: { key: "herdier", name: "Ponchien", dexNumber: 507, types: ["normal"], baseAttack: 12, baseHp: 35, baseCaptureRate: 0.3, rarityWeight: 1, spriteFile: "herdier.png", spriteScale: 0.85, evolution: { intoKey: "stoutland", level: 32 } },
  stoutland: { key: "stoutland", name: "Mastouffe", dexNumber: 508, types: ["normal"], baseAttack: 17, baseHp: 46, baseCaptureRate: 0.18, rarityWeight: 1, spriteFile: "stoutland.png", spriteScale: 0.88 },
  eevee: {
    key: "eevee",
    name: "Évoli",
    dexNumber: 133,
    types: ["normal"],
    baseAttack: 10,
    baseHp: 26,
    baseCaptureRate: 0.35,
    rarityWeight: 6,
    spriteFile: "eevee.png",
    spriteScale: 0.75,
    stoneEvolutions: [
      { stoneKey: "pierre_feu", intoKey: "flareon" },
      { stoneKey: "pierre_eau", intoKey: "vaporeon" },
      { stoneKey: "pierre_foudre", intoKey: "jolteon" },
      { stoneKey: "pierre_feuille", intoKey: "leafeon" },
    ],
  },
  flareon: { key: "flareon", name: "Pyroli", dexNumber: 136, types: ["feu"], baseAttack: 15, baseHp: 33, baseCaptureRate: 0.21, rarityWeight: 1, spriteFile: "flareon.png", spriteScale: 0.85 },
  vaporeon: { key: "vaporeon", name: "Aquali", dexNumber: 134, types: ["eau"], baseAttack: 13, baseHp: 46, baseCaptureRate: 0.21, rarityWeight: 1, spriteFile: "vaporeon.png", spriteScale: 0.86 },
  jolteon: { key: "jolteon", name: "Voltali", dexNumber: 135, types: ["electrique"], baseAttack: 17, baseHp: 29, baseCaptureRate: 0.21, rarityWeight: 1, spriteFile: "jolteon.png", spriteScale: 0.84 },
  leafeon: { key: "leafeon", name: "Phyllali", dexNumber: 470, types: ["plante"], baseAttack: 16, baseHp: 30, baseCaptureRate: 0.21, rarityWeight: 1, spriteFile: "leafeon.png", spriteScale: 0.86 },

  // --- Route 3 (normal, mid tier — evolved forms of Route 1's family) ---
  raticate: { key: "raticate", name: "Rattatac", dexNumber: 20, types: ["normal"], baseAttack: 14, baseHp: 30, baseCaptureRate: 0.35, rarityWeight: 10000, spriteFile: "raticate.png", spriteScale: 0.83 },
  linoone: { key: "linoone", name: "Linéon", dexNumber: 264, types: ["normal"], baseAttack: 15, baseHp: 28, baseCaptureRate: 0.35, rarityWeight: 7000, spriteFile: "linoone.png", spriteScale: 0.79 },
  furret: { key: "furret", name: "Fouinar", dexNumber: 162, types: ["normal"], baseAttack: 13, baseHp: 32, baseCaptureRate: 0.35, rarityWeight: 4000, spriteFile: "furret.png", spriteScale: 0.93 },
  meowth: { key: "meowth", name: "Miaouss", dexNumber: 52, types: ["normal"], baseAttack: 12, baseHp: 26, baseCaptureRate: 0.4, rarityWeight: 2500, spriteFile: "meowth.png", spriteScale: 0.78, evolution: { intoKey: "persian", level: 28 } },
  persian: { key: "persian", name: "Persian", dexNumber: 53, types: ["normal"], baseAttack: 18, baseHp: 33, baseCaptureRate: 0.24, rarityWeight: 1, spriteFile: "persian.png", spriteScale: 0.86 },
  buneary: { key: "buneary", name: "Laporeille", dexNumber: 427, types: ["normal"], baseAttack: 11, baseHp: 28, baseCaptureRate: 0.4, rarityWeight: 1499, spriteFile: "buneary.png", spriteScale: 0.78 },

  // --- Route 2 (plante, low-mid tier) ---
  shroomish: { key: "shroomish", name: "Balignon", dexNumber: 285, types: ["plante"], baseAttack: 9, baseHp: 30, baseCaptureRate: 0.45, rarityWeight: 32, spriteFile: "shroomish.png", spriteScale: 0.78, evolution: { intoKey: "breloom", level: 23 } },
  breloom: { key: "breloom", name: "Chapignon", dexNumber: 286, types: ["plante", "combat"], baseAttack: 14, baseHp: 38, baseCaptureRate: 0.27, rarityWeight: 1, spriteFile: "breloom.png", spriteScale: 0.88 },
  budew: { key: "budew", name: "Rozbouton", dexNumber: 406, types: ["plante", "poison"], baseAttack: 8, baseHp: 26, baseCaptureRate: 0.45, rarityWeight: 26, spriteFile: "budew.png", spriteScale: 0.73 },
  cottonee: { key: "cottonee", name: "Doudouvet", dexNumber: 546, types: ["plante", "fee"], baseAttack: 7, baseHp: 24, baseCaptureRate: 0.5, rarityWeight: 20, spriteFile: "cottonee.png", spriteScale: 0.75, stoneEvolutions: [{ stoneKey: "pierre_soleil", intoKey: "whimsicott" }] },
  whimsicott: { key: "whimsicott", name: "Farfaduvet", dexNumber: 547, types: ["plante", "fee"], baseAttack: 13, baseHp: 32, baseCaptureRate: 0.3, rarityWeight: 1, spriteFile: "whimsicott.png", spriteScale: 0.83 },
  bellsprout: { key: "bellsprout", name: "Chétiflor", dexNumber: 69, types: ["plante", "poison"], baseAttack: 10, baseHp: 24, baseCaptureRate: 0.42, rarityWeight: 14, spriteFile: "bellsprout.png", spriteScale: 0.83, evolution: { intoKey: "weepinbell", level: 21 } },
  weepinbell: { key: "weepinbell", name: "Boustiflor", dexNumber: 70, types: ["plante", "poison"], baseAttack: 15, baseHp: 30, baseCaptureRate: 0.25, rarityWeight: 1, spriteFile: "weepinbell.png", spriteScale: 0.86, stoneEvolutions: [{ stoneKey: "pierre_feuille", intoKey: "victreebel" }] },
  victreebel: { key: "victreebel", name: "Empiflor", dexNumber: 71, types: ["plante", "poison"], baseAttack: 22, baseHp: 38, baseCaptureRate: 0.15, rarityWeight: 1, spriteFile: "victreebel.png", spriteScale: 0.93 },
  sunkern: { key: "sunkern", name: "Tournegrin", dexNumber: 191, types: ["plante"], baseAttack: 6, baseHp: 22, baseCaptureRate: 0.55, rarityWeight: 8, spriteFile: "sunkern.png", spriteScale: 0.75, stoneEvolutions: [{ stoneKey: "pierre_soleil", intoKey: "sunflora" }] },
  sunflora: { key: "sunflora", name: "Héliatronc", dexNumber: 192, types: ["plante"], baseAttack: 11, baseHp: 30, baseCaptureRate: 0.35, rarityWeight: 1, spriteFile: "sunflora.png", spriteScale: 0.84 },

  // --- Route 4 (eau, mid tier) ---
  poliwag: { key: "poliwag", name: "Ptitard", dexNumber: 60, types: ["eau"], baseAttack: 11, baseHp: 28, baseCaptureRate: 0.42, rarityWeight: 32, spriteFile: "poliwag.png", spriteScale: 0.81, evolution: { intoKey: "poliwhirl", level: 25 } },
  poliwhirl: { key: "poliwhirl", name: "Têtarte", dexNumber: 61, types: ["eau"], baseAttack: 17, baseHp: 35, baseCaptureRate: 0.25, rarityWeight: 1, spriteFile: "poliwhirl.png", spriteScale: 0.86, stoneEvolutions: [{ stoneKey: "pierre_eau", intoKey: "poliwrath" }] },
  poliwrath: { key: "poliwrath", name: "Tartard", dexNumber: 62, types: ["eau", "combat"], baseAttack: 26, baseHp: 44, baseCaptureRate: 0.15, rarityWeight: 1, spriteFile: "poliwrath.png", spriteScale: 0.89 },
  psyduck: { key: "psyduck", name: "Psykokwak", dexNumber: 54, types: ["eau"], baseAttack: 12, baseHp: 30, baseCaptureRate: 0.4, rarityWeight: 26, spriteFile: "psyduck.png", spriteScale: 0.84, evolution: { intoKey: "golduck", level: 33 } },
  golduck: { key: "golduck", name: "Akwakwak", dexNumber: 55, types: ["eau"], baseAttack: 18, baseHp: 38, baseCaptureRate: 0.24, rarityWeight: 1, spriteFile: "golduck.png", spriteScale: 0.93 },
  horsea: { key: "horsea", name: "Hypotrempe", dexNumber: 116, types: ["eau"], baseAttack: 13, baseHp: 24, baseCaptureRate: 0.38, rarityWeight: 20, spriteFile: "horsea.png", spriteScale: 0.78, evolution: { intoKey: "seadra", level: 32 } },
  seadra: { key: "seadra", name: "Hypocéan", dexNumber: 117, types: ["eau"], baseAttack: 20, baseHp: 30, baseCaptureRate: 0.23, rarityWeight: 1, spriteFile: "seadra.png", spriteScale: 0.88 },
  staryu: { key: "staryu", name: "Stari", dexNumber: 120, types: ["eau"], baseAttack: 12, baseHp: 26, baseCaptureRate: 0.4, rarityWeight: 14, spriteFile: "staryu.png", spriteScale: 0.84, stoneEvolutions: [{ stoneKey: "pierre_eau", intoKey: "starmie" }] },
  starmie: { key: "starmie", name: "Staross", dexNumber: 121, types: ["eau", "psy"], baseAttack: 19, baseHp: 33, baseCaptureRate: 0.18, rarityWeight: 1, spriteFile: "starmie.png", spriteScale: 0.87 },
  wooper: { key: "wooper", name: "Axoloto", dexNumber: 194, types: ["eau", "sol"], baseAttack: 10, baseHp: 32, baseCaptureRate: 0.45, rarityWeight: 8, spriteFile: "wooper.png", spriteScale: 0.78, evolution: { intoKey: "quagsire", level: 20 } },
  quagsire: { key: "quagsire", name: "Maraiste", dexNumber: 195, types: ["eau", "sol"], baseAttack: 15, baseHp: 40, baseCaptureRate: 0.27, rarityWeight: 1, spriteFile: "quagsire.png", spriteScale: 0.9 },

  // --- Égouts Sombres dungeon (eau, low-mid tier — starter babies + Magikarp) ---
  squirtle: { key: "squirtle", name: "Carapuce", dexNumber: 7, types: ["eau"], baseAttack: 11, baseHp: 30, baseCaptureRate: 0.35, rarityWeight: 26, spriteFile: "squirtle.png", spriteScale: 0.79, evolution: { intoKey: "wartortle", level: 16 } },
  wartortle: { key: "wartortle", name: "Carabaffe", dexNumber: 8, types: ["eau"], baseAttack: 14, baseHp: 40, baseCaptureRate: 0.21, rarityWeight: 1, spriteFile: "wartortle.png", spriteScale: 0.86, evolution: { intoKey: "blastoise", level: 36 } },
  blastoise: { key: "blastoise", name: "Tortank", dexNumber: 9, types: ["eau"], baseAttack: 18, baseHp: 54, baseCaptureRate: 0.13, rarityWeight: 1, spriteFile: "blastoise.png", spriteScale: 0.92 },
  totodile: { key: "totodile", name: "Kaiminus", dexNumber: 158, types: ["eau"], baseAttack: 13, baseHp: 28, baseCaptureRate: 0.32, rarityWeight: 22, spriteFile: "totodile.png", spriteScale: 0.81, evolution: { intoKey: "croconaw", level: 18 } },
  croconaw: { key: "croconaw", name: "Crocrodil", dexNumber: 159, types: ["eau"], baseAttack: 16, baseHp: 36, baseCaptureRate: 0.19, rarityWeight: 1, spriteFile: "croconaw.png", spriteScale: 0.87, evolution: { intoKey: "feraligatr", level: 30 } },
  feraligatr: { key: "feraligatr", name: "Aligatueur", dexNumber: 160, types: ["eau"], baseAttack: 21, baseHp: 47, baseCaptureRate: 0.11, rarityWeight: 1, spriteFile: "feraligatr.png", spriteScale: 0.97 },
  mudkip: { key: "mudkip", name: "Gobou", dexNumber: 258, types: ["eau"], baseAttack: 12, baseHp: 30, baseCaptureRate: 0.32, rarityWeight: 18, spriteFile: "mudkip.png", spriteScale: 0.78, evolution: { intoKey: "marshtomp", level: 16 } },
  marshtomp: { key: "marshtomp", name: "Flobio", dexNumber: 259, types: ["eau", "sol"], baseAttack: 15, baseHp: 42, baseCaptureRate: 0.19, rarityWeight: 1, spriteFile: "marshtomp.png", spriteScale: 0.83, evolution: { intoKey: "swampert", level: 36 } },
  swampert: { key: "swampert", name: "Laggron", dexNumber: 260, types: ["eau", "sol"], baseAttack: 19, baseHp: 60, baseCaptureRate: 0.11, rarityWeight: 1, spriteFile: "swampert.png", spriteScale: 0.91 },
  piplup: { key: "piplup", name: "Tiplouf", dexNumber: 393, types: ["eau"], baseAttack: 11, baseHp: 28, baseCaptureRate: 0.32, rarityWeight: 14, spriteFile: "piplup.png", spriteScale: 0.78, evolution: { intoKey: "prinplup", level: 16 } },
  prinplup: { key: "prinplup", name: "Prinplouf", dexNumber: 394, types: ["eau"], baseAttack: 14, baseHp: 34, baseCaptureRate: 0.19, rarityWeight: 1, spriteFile: "prinplup.png", spriteScale: 0.84, evolution: { intoKey: "empoleon", level: 36 } },
  empoleon: { key: "empoleon", name: "Pingoléon", dexNumber: 395, types: ["eau", "acier"], baseAttack: 18, baseHp: 45, baseCaptureRate: 0.11, rarityWeight: 1, spriteFile: "empoleon.png", spriteScale: 0.93 },
  magikarp: { key: "magikarp", name: "Magicarpe", dexNumber: 129, types: ["eau"], baseAttack: 4, baseHp: 20, baseCaptureRate: 0.6, rarityWeight: 40, spriteFile: "magikarp.png", spriteScale: 0.85, evolution: { intoKey: "gyarados", level: 20 } },
  gyarados: { key: "gyarados", name: "Léviator", dexNumber: 130, types: ["eau", "vol"], baseAttack: 35, baseHp: 55, baseCaptureRate: 0.15, rarityWeight: 1, spriteFile: "gyarados.png", spriteScale: 1.15 },

  // --- Crypte des Anciens dungeon (feu, low-mid tier — starter babies) ---
  growlithe: { key: "growlithe", name: "Caninos", dexNumber: 58, types: ["feu"], baseAttack: 14, baseHp: 26, baseCaptureRate: 0.35, rarityWeight: 30, spriteFile: "growlithe.png", spriteScale: 0.83, stoneEvolutions: [{ stoneKey: "pierre_feu", intoKey: "arcanine" }] },
  cyndaquil: { key: "cyndaquil", name: "Héricendre", dexNumber: 155, types: ["feu"], baseAttack: 13, baseHp: 24, baseCaptureRate: 0.3, rarityWeight: 22, spriteFile: "cyndaquil.png", spriteScale: 0.79, evolution: { intoKey: "quilava", level: 14 } },
  quilava: { key: "quilava", name: "Feurisson", dexNumber: 156, types: ["feu"], baseAttack: 16, baseHp: 36, baseCaptureRate: 0.18, rarityWeight: 1, spriteFile: "quilava.png", spriteScale: 0.85, evolution: { intoKey: "typhlosion", level: 36 } },
  typhlosion: { key: "typhlosion", name: "Typhlosion", dexNumber: 157, types: ["feu"], baseAttack: 21, baseHp: 48, baseCaptureRate: 0.11, rarityWeight: 1, spriteFile: "typhlosion.png", spriteScale: 0.93 },
  torchic: { key: "torchic", name: "Poussifeu", dexNumber: 255, types: ["feu"], baseAttack: 13, baseHp: 22, baseCaptureRate: 0.3, rarityWeight: 18, spriteFile: "torchic.png", spriteScale: 0.78, evolution: { intoKey: "combusken", level: 16 } },
  combusken: { key: "combusken", name: "Galifeu", dexNumber: 256, types: ["feu", "combat"], baseAttack: 18, baseHp: 29, baseCaptureRate: 0.18, rarityWeight: 1, spriteFile: "combusken.png", spriteScale: 0.85, evolution: { intoKey: "blaziken", level: 36 } },
  blaziken: { key: "blaziken", name: "Braségali", dexNumber: 257, types: ["feu", "combat"], baseAttack: 25, baseHp: 39, baseCaptureRate: 0.11, rarityWeight: 1, spriteFile: "blaziken.png", spriteScale: 0.94 },
  chimchar: { key: "chimchar", name: "Ouisticram", dexNumber: 390, types: ["feu"], baseAttack: 14, baseHp: 22, baseCaptureRate: 0.3, rarityWeight: 14, spriteFile: "chimchar.png", spriteScale: 0.79, evolution: { intoKey: "monferno", level: 14 } },
  monferno: { key: "monferno", name: "Chimpenfeu", dexNumber: 391, types: ["feu", "combat"], baseAttack: 19, baseHp: 32, baseCaptureRate: 0.18, rarityWeight: 1, spriteFile: "monferno.png", spriteScale: 0.85, evolution: { intoKey: "infernape", level: 36 } },
  infernape: { key: "infernape", name: "Simiabraz", dexNumber: 392, types: ["feu", "combat"], baseAttack: 25, baseHp: 38, baseCaptureRate: 0.11, rarityWeight: 1, spriteFile: "infernape.png", spriteScale: 0.88 },
  numel: { key: "numel", name: "Chamallot", dexNumber: 322, types: ["feu", "sol"], baseAttack: 11, baseHp: 30, baseCaptureRate: 0.4, rarityWeight: 8, spriteFile: "numel.png", spriteScale: 0.83, evolution: { intoKey: "camerupt", level: 33 } },

  // --- Route 7 (feu, high tier — evolved forms) ---
  arcanine: { key: "arcanine", name: "Arcanin", dexNumber: 59, types: ["feu"], baseAttack: 24, baseHp: 46, baseCaptureRate: 0.2, rarityWeight: 30, spriteFile: "arcanine.png", spriteScale: 0.94 },
  rapidash: { key: "rapidash", name: "Galopa", dexNumber: 78, types: ["feu"], baseAttack: 22, baseHp: 38, baseCaptureRate: 0.22, rarityWeight: 24, spriteFile: "rapidash.png", spriteScale: 0.93 },
  magmar: { key: "magmar", name: "Magmar", dexNumber: 126, types: ["feu"], baseAttack: 23, baseHp: 36, baseCaptureRate: 0.22, rarityWeight: 18, spriteFile: "magmar.png", spriteScale: 0.89 },
  torkoal: { key: "torkoal", name: "Chartor", dexNumber: 324, types: ["feu"], baseAttack: 18, baseHp: 42, baseCaptureRate: 0.25, rarityWeight: 12, spriteFile: "torkoal.png", spriteScale: 0.79 },
  camerupt: { key: "camerupt", name: "Camérupt", dexNumber: 323, types: ["feu", "sol"], baseAttack: 22, baseHp: 44, baseCaptureRate: 0.22, rarityWeight: 8, spriteFile: "camerupt.png", spriteScale: 0.94 },

  // --- Usine Abandonnée dungeon (electrique, low-mid tier — basic forms) ---
  pikachu: { key: "pikachu", name: "Pikachu", dexNumber: 25, types: ["electrique"], baseAttack: 13, baseHp: 24, baseCaptureRate: 0.3, rarityWeight: 10, spriteFile: "pikachu.png", spriteScale: 0.78, stoneEvolutions: [{ stoneKey: "pierre_foudre", intoKey: "raichu" }] },
  magnemite: { key: "magnemite", name: "Magnéti", dexNumber: 81, types: ["electrique", "acier"], baseAttack: 12, baseHp: 20, baseCaptureRate: 0.4, rarityWeight: 28, spriteFile: "magnemite.png", spriteScale: 0.75, evolution: { intoKey: "magneton", level: 30 } },
  magneton: { key: "magneton", name: "Magnéton", dexNumber: 82, types: ["electrique", "acier"], baseAttack: 18, baseHp: 25, baseCaptureRate: 0.24, rarityWeight: 1, spriteFile: "magneton.png", spriteScale: 0.86 },
  voltorb: { key: "voltorb", name: "Voltorbe", dexNumber: 100, types: ["electrique"], baseAttack: 11, baseHp: 22, baseCaptureRate: 0.4, rarityWeight: 24, spriteFile: "voltorb.png", spriteScale: 0.79, evolution: { intoKey: "electrode", level: 30 } },
  electrode: { key: "electrode", name: "Électrode", dexNumber: 101, types: ["electrique"], baseAttack: 17, baseHp: 28, baseCaptureRate: 0.24, rarityWeight: 1, spriteFile: "electrode.png", spriteScale: 0.88 },
  mareep: { key: "mareep", name: "Wattouat", dexNumber: 179, types: ["electrique"], baseAttack: 10, baseHp: 26, baseCaptureRate: 0.42, rarityWeight: 20, spriteFile: "mareep.png", spriteScale: 0.81, evolution: { intoKey: "flaaffy", level: 15 } },
  flaaffy: { key: "flaaffy", name: "Lainergie", dexNumber: 180, types: ["electrique"], baseAttack: 14, baseHp: 33, baseCaptureRate: 0.25, rarityWeight: 1, spriteFile: "flaaffy.png", spriteScale: 0.84, evolution: { intoKey: "ampharos", level: 30 } },
  shinx: { key: "shinx", name: "Lixy", dexNumber: 403, types: ["electrique"], baseAttack: 13, baseHp: 24, baseCaptureRate: 0.35, rarityWeight: 14, spriteFile: "shinx.png", spriteScale: 0.79, evolution: { intoKey: "luxio", level: 15 } },
  luxio: { key: "luxio", name: "Luxio", dexNumber: 404, types: ["electrique"], baseAttack: 17, baseHp: 32, baseCaptureRate: 0.21, rarityWeight: 1, spriteFile: "luxio.png", spriteScale: 0.85, evolution: { intoKey: "luxray", level: 30 } },

  // --- Route 9 (electrique, highest tier — evolved forms) ---
  raichu: { key: "raichu", name: "Raichu", dexNumber: 26, types: ["electrique"], baseAttack: 26, baseHp: 38, baseCaptureRate: 0.18, rarityWeight: 24, spriteFile: "raichu.png", spriteScale: 0.84 },
  magnezone: { key: "magnezone", name: "Magnézone", dexNumber: 462, types: ["electrique", "acier"], baseAttack: 25, baseHp: 40, baseCaptureRate: 0.18, rarityWeight: 20, spriteFile: "magnezone.png", spriteScale: 0.88 },
  electivire: { key: "electivire", name: "Élekable", dexNumber: 466, types: ["electrique"], baseAttack: 27, baseHp: 42, baseCaptureRate: 0.16, rarityWeight: 16, spriteFile: "electivire.png", spriteScale: 0.93 },
  ampharos: { key: "ampharos", name: "Pharamp", dexNumber: 181, types: ["electrique"], baseAttack: 24, baseHp: 46, baseCaptureRate: 0.2, rarityWeight: 12, spriteFile: "ampharos.png", spriteScale: 0.9 },
  luxray: { key: "luxray", name: "Luxray", dexNumber: 405, types: ["electrique"], baseAttack: 26, baseHp: 36, baseCaptureRate: 0.18, rarityWeight: 8, spriteFile: "luxray.png", spriteScale: 0.9 },

  // === Mont Cendre region (routes 2-13, niv. 25-60) - 100 new species, French names verified via PokeAPI ===
  abra: { key: "abra", name: "Abra", dexNumber: 63, types: ["psy"], baseAttack: 22, baseHp: 36, baseCaptureRate: 0.3, rarityWeight: 28, spriteFile: "abra.png", spriteScale: 0.85, evolution: { intoKey: "kadabra", level: 16 } },
  kadabra: { key: "kadabra", name: "Kadabra", dexNumber: 64, types: ["psy"], baseAttack: 26, baseHp: 44, baseCaptureRate: 0.16, rarityWeight: 1, spriteFile: "kadabra.png", spriteScale: 0.89, evolution: { intoKey: "alakazam", level: 36 } },
  alakazam: { key: "alakazam", name: "Alakazam", dexNumber: 65, types: ["psy"], baseAttack: 30, baseHp: 50, baseCaptureRate: 0.1, rarityWeight: 1, spriteFile: "alakazam.png", spriteScale: 0.91 },
  machop: { key: "machop", name: "Machoc", dexNumber: 66, types: ["combat"], baseAttack: 20, baseHp: 44, baseCaptureRate: 0.35, rarityWeight: 30, spriteFile: "machop.png", spriteScale: 0.84, evolution: { intoKey: "machoke", level: 28 } },
  machoke: { key: "machoke", name: "Machopeur", dexNumber: 67, types: ["combat"], baseAttack: 24, baseHp: 50, baseCaptureRate: 0.18, rarityWeight: 1, spriteFile: "machoke.png", spriteScale: 0.91, evolution: { intoKey: "machamp", level: 36 } },
  machamp: { key: "machamp", name: "Mackogneur", dexNumber: 68, types: ["combat"], baseAttack: 28, baseHp: 56, baseCaptureRate: 0.11, rarityWeight: 1, spriteFile: "machamp.png", spriteScale: 0.92 },
  tentacool: { key: "tentacool", name: "Tentacool", dexNumber: 72, types: ["eau", "poison"], baseAttack: 18, baseHp: 42, baseCaptureRate: 0.35, rarityWeight: 30, spriteFile: "tentacool.png", spriteScale: 0.85, evolution: { intoKey: "tentacruel", level: 30 } },
  tentacruel: { key: "tentacruel", name: "Tentacruel", dexNumber: 73, types: ["eau", "poison"], baseAttack: 25, baseHp: 52, baseCaptureRate: 0.14, rarityWeight: 1, spriteFile: "tentacruel.png", spriteScale: 0.92 },
  geodude: { key: "geodude", name: "Racaillou", dexNumber: 74, types: ["roche", "sol"], baseAttack: 18, baseHp: 44, baseCaptureRate: 0.4, rarityWeight: 30, spriteFile: "geodude.png", spriteScale: 0.78, evolution: { intoKey: "graveler", level: 25 } },
  graveler: { key: "graveler", name: "Gravalanch", dexNumber: 75, types: ["roche", "sol"], baseAttack: 21, baseHp: 50, baseCaptureRate: 0.2, rarityWeight: 1, spriteFile: "graveler.png", spriteScale: 0.86, evolution: { intoKey: "golem", level: 36 } },
  golem: { key: "golem", name: "Grolem", dexNumber: 76, types: ["roche", "sol"], baseAttack: 24, baseHp: 56, baseCaptureRate: 0.14, rarityWeight: 1, spriteFile: "golem.png", spriteScale: 0.9 },
  grimer: { key: "grimer", name: "Tadmorv", dexNumber: 88, types: ["poison"], baseAttack: 20, baseHp: 48, baseCaptureRate: 0.3, rarityWeight: 24, spriteFile: "grimer.png", spriteScale: 0.85, evolution: { intoKey: "muk", level: 38 } },
  muk: { key: "muk", name: "Grotadmorv", dexNumber: 89, types: ["poison"], baseAttack: 26, baseHp: 56, baseCaptureRate: 0.13, rarityWeight: 1, spriteFile: "muk.png", spriteScale: 0.88 },
  gastly: { key: "gastly", name: "Fantominus", dexNumber: 92, types: ["spectre", "poison"], baseAttack: 22, baseHp: 40, baseCaptureRate: 0.2, rarityWeight: 22, spriteFile: "gastly.png", spriteScale: 0.89, evolution: { intoKey: "haunter", level: 25 } },
  haunter: { key: "haunter", name: "Spectrum", dexNumber: 93, types: ["spectre", "poison"], baseAttack: 26, baseHp: 46, baseCaptureRate: 0.14, rarityWeight: 1, spriteFile: "haunter.png", spriteScale: 0.92, evolution: { intoKey: "gengar", level: 38 } },
  gengar: { key: "gengar", name: "Ectoplasma", dexNumber: 94, types: ["spectre", "poison"], baseAttack: 31, baseHp: 54, baseCaptureRate: 0.09, rarityWeight: 1, spriteFile: "gengar.png", spriteScale: 0.91 },
  onix: { key: "onix", name: "Onix", dexNumber: 95, types: ["roche", "sol"], baseAttack: 16, baseHp: 54, baseCaptureRate: 0.3, rarityWeight: 22, spriteFile: "onix.png", spriteScale: 1.15 },
  drowzee: { key: "drowzee", name: "Soporifik", dexNumber: 96, types: ["psy"], baseAttack: 18, baseHp: 46, baseCaptureRate: 0.32, rarityWeight: 20, spriteFile: "drowzee.png", spriteScale: 0.86, evolution: { intoKey: "hypno", level: 26 } },
  hypno: { key: "hypno", name: "Hypnomade", dexNumber: 97, types: ["psy"], baseAttack: 25, baseHp: 54, baseCaptureRate: 0.14, rarityWeight: 1, spriteFile: "hypno.png", spriteScale: 0.92 },
  rhyhorn: { key: "rhyhorn", name: "Rhinocorne", dexNumber: 111, types: ["sol", "roche"], baseAttack: 20, baseHp: 50, baseCaptureRate: 0.35, rarityWeight: 20, spriteFile: "rhyhorn.png", spriteScale: 0.86, evolution: { intoKey: "rhydon", level: 42 } },
  rhydon: { key: "rhydon", name: "Rhinoféros", dexNumber: 112, types: ["sol", "roche"], baseAttack: 25, baseHp: 56, baseCaptureRate: 0.16, rarityWeight: 1, spriteFile: "rhydon.png", spriteScale: 0.94, evolution: { intoKey: "rhyperior", level: 55 } },
  kangaskhan: { key: "kangaskhan", name: "Kangourex", dexNumber: 115, types: ["normal"], baseAttack: 24, baseHp: 54, baseCaptureRate: 0.2, rarityWeight: 16, spriteFile: "kangaskhan.png", spriteScale: 0.96 },
  scyther: { key: "scyther", name: "Insécateur", dexNumber: 123, types: ["insecte", "vol"], baseAttack: 26, baseHp: 48, baseCaptureRate: 0.2, rarityWeight: 24, spriteFile: "scyther.png", spriteScale: 0.91 },
  pinsir: { key: "pinsir", name: "Scarabrute", dexNumber: 127, types: ["insecte"], baseAttack: 26, baseHp: 50, baseCaptureRate: 0.2, rarityWeight: 14, spriteFile: "pinsir.png", spriteScale: 0.91 },
  tauros: { key: "tauros", name: "Tauros", dexNumber: 128, types: ["normal"], baseAttack: 24, baseHp: 48, baseCaptureRate: 0.25, rarityWeight: 26, spriteFile: "tauros.png", spriteScale: 0.9 },
  snorlax: { key: "snorlax", name: "Ronflex", dexNumber: 143, types: ["normal"], baseAttack: 24, baseHp: 64, baseCaptureRate: 0.15, rarityWeight: 8, spriteFile: "snorlax.png", spriteScale: 0.95 },
  dratini: { key: "dratini", name: "Minidraco", dexNumber: 147, types: ["dragon"], baseAttack: 22, baseHp: 50, baseCaptureRate: 0.13, rarityWeight: 16, spriteFile: "dratini.png", spriteScale: 0.93, evolution: { intoKey: "dragonair", level: 30 } },
  dragonair: { key: "dragonair", name: "Draco", dexNumber: 148, types: ["dragon"], baseAttack: 27, baseHp: 56, baseCaptureRate: 0.1, rarityWeight: 1, spriteFile: "dragonair.png", spriteScale: 1.06, evolution: { intoKey: "dragonite", level: 55 } },
  dragonite: { key: "dragonite", name: "Dracolosse", dexNumber: 149, types: ["dragon", "vol"], baseAttack: 33, baseHp: 64, baseCaptureRate: 0.06, rarityWeight: 1, spriteFile: "dragonite.png", spriteScale: 0.96 },
  murkrow: { key: "murkrow", name: "Cornèbre", dexNumber: 198, types: ["tenebres", "vol"], baseAttack: 24, baseHp: 42, baseCaptureRate: 0.22, rarityWeight: 16, spriteFile: "murkrow.png", spriteScale: 0.79, evolution: { intoKey: "honchkrow", level: 45 } },
  girafarig: { key: "girafarig", name: "Girafarig", dexNumber: 203, types: ["normal", "psy"], baseAttack: 22, baseHp: 46, baseCaptureRate: 0.28, rarityWeight: 14, spriteFile: "girafarig.png", spriteScale: 0.91 },
  gligar: { key: "gligar", name: "Scorplane", dexNumber: 207, types: ["sol", "vol"], baseAttack: 22, baseHp: 46, baseCaptureRate: 0.28, rarityWeight: 16, spriteFile: "gligar.png", spriteScale: 0.87 },
  qwilfish: { key: "qwilfish", name: "Qwilfish", dexNumber: 211, types: ["eau", "poison"], baseAttack: 22, baseHp: 44, baseCaptureRate: 0.3, rarityWeight: 12, spriteFile: "qwilfish.png", spriteScale: 0.79 },
  heracross: { key: "heracross", name: "Scarhino", dexNumber: 214, types: ["insecte", "combat"], baseAttack: 28, baseHp: 52, baseCaptureRate: 0.18, rarityWeight: 18, spriteFile: "heracross.png", spriteScale: 0.91 },
  sneasel: { key: "sneasel", name: "Farfuret", dexNumber: 215, types: ["tenebres", "glace"], baseAttack: 26, baseHp: 44, baseCaptureRate: 0.22, rarityWeight: 20, spriteFile: "sneasel.png", spriteScale: 0.85, evolution: { intoKey: "weavile", level: 45 } },
  slugma: { key: "slugma", name: "Limagma", dexNumber: 218, types: ["feu"], baseAttack: 18, baseHp: 40, baseCaptureRate: 0.35, rarityWeight: 30, spriteFile: "slugma.png", spriteScale: 0.83, evolution: { intoKey: "magcargo", level: 38 } },
  magcargo: { key: "magcargo", name: "Volcaropod", dexNumber: 219, types: ["feu", "roche"], baseAttack: 23, baseHp: 50, baseCaptureRate: 0.15, rarityWeight: 1, spriteFile: "magcargo.png", spriteScale: 0.84 },
  swinub: { key: "swinub", name: "Marcacrin", dexNumber: 220, types: ["glace", "sol"], baseAttack: 18, baseHp: 46, baseCaptureRate: 0.3, rarityWeight: 26, spriteFile: "swinub.png", spriteScale: 0.78, evolution: { intoKey: "piloswine", level: 33 } },
  piloswine: { key: "piloswine", name: "Cochignon", dexNumber: 221, types: ["glace", "sol"], baseAttack: 25, baseHp: 56, baseCaptureRate: 0.15, rarityWeight: 1, spriteFile: "piloswine.png", spriteScale: 0.87, evolution: { intoKey: "mamoswine", level: 50 } },
  skarmory: { key: "skarmory", name: "Airmure", dexNumber: 227, types: ["acier", "vol"], baseAttack: 22, baseHp: 50, baseCaptureRate: 0.25, rarityWeight: 14, spriteFile: "skarmory.png", spriteScale: 0.93 },
  houndour: { key: "houndour", name: "Malosse", dexNumber: 228, types: ["tenebres", "feu"], baseAttack: 20, baseHp: 40, baseCaptureRate: 0.3, rarityWeight: 18, spriteFile: "houndour.png", spriteScale: 0.81, evolution: { intoKey: "houndoom", level: 24 } },
  houndoom: { key: "houndoom", name: "Démolosse", dexNumber: 229, types: ["tenebres", "feu"], baseAttack: 25, baseHp: 48, baseCaptureRate: 0.13, rarityWeight: 1, spriteFile: "houndoom.png", spriteScale: 0.9 },
  phanpy: { key: "phanpy", name: "Phanpy", dexNumber: 231, types: ["sol"], baseAttack: 18, baseHp: 48, baseCaptureRate: 0.35, rarityWeight: 24, spriteFile: "phanpy.png", spriteScale: 0.79, evolution: { intoKey: "donphan", level: 25 } },
  donphan: { key: "donphan", name: "Donphan", dexNumber: 232, types: ["sol"], baseAttack: 26, baseHp: 56, baseCaptureRate: 0.15, rarityWeight: 1, spriteFile: "donphan.png", spriteScale: 0.87 },
  miltank: { key: "miltank", name: "Écrémeuh", dexNumber: 241, types: ["normal"], baseAttack: 20, baseHp: 54, baseCaptureRate: 0.25, rarityWeight: 22, spriteFile: "miltank.png", spriteScale: 0.88 },
  larvitar: { key: "larvitar", name: "Embrylex", dexNumber: 246, types: ["roche", "sol"], baseAttack: 22, baseHp: 48, baseCaptureRate: 0.22, rarityWeight: 20, spriteFile: "larvitar.png", spriteScale: 0.81, evolution: { intoKey: "pupitar", level: 30 } },
  pupitar: { key: "pupitar", name: "Ymphect", dexNumber: 247, types: ["roche", "sol"], baseAttack: 26, baseHp: 54, baseCaptureRate: 0.14, rarityWeight: 1, spriteFile: "pupitar.png", spriteScale: 0.88, evolution: { intoKey: "tyranitar", level: 55 } },
  tyranitar: { key: "tyranitar", name: "Tyranocif", dexNumber: 248, types: ["roche", "tenebres"], baseAttack: 32, baseHp: 64, baseCaptureRate: 0.08, rarityWeight: 1, spriteFile: "tyranitar.png", spriteScale: 0.95 },
  poochyena: { key: "poochyena", name: "Medhyèna", dexNumber: 261, types: ["tenebres"], baseAttack: 22, baseHp: 44, baseCaptureRate: 0.3, rarityWeight: 28, spriteFile: "poochyena.png", spriteScale: 0.79, evolution: { intoKey: "mightyena", level: 18 } },
  mightyena: { key: "mightyena", name: "Grahyèna", dexNumber: 262, types: ["tenebres"], baseAttack: 27, baseHp: 52, baseCaptureRate: 0.14, rarityWeight: 1, spriteFile: "mightyena.png", spriteScale: 0.86 },
  ralts: { key: "ralts", name: "Tarsal", dexNumber: 280, types: ["psy", "fee"], baseAttack: 18, baseHp: 38, baseCaptureRate: 0.3, rarityWeight: 22, spriteFile: "ralts.png", spriteScale: 0.78, evolution: { intoKey: "kirlia", level: 20 } },
  kirlia: { key: "kirlia", name: "Kirlia", dexNumber: 281, types: ["psy", "fee"], baseAttack: 22, baseHp: 44, baseCaptureRate: 0.16, rarityWeight: 1, spriteFile: "kirlia.png", spriteScale: 0.84, evolution: { intoKey: "gardevoir", level: 30 } },
  gardevoir: { key: "gardevoir", name: "Gardevoir", dexNumber: 282, types: ["psy", "fee"], baseAttack: 27, baseHp: 52, baseCaptureRate: 0.11, rarityWeight: 1, spriteFile: "gardevoir.png", spriteScale: 0.92 },
  nincada: { key: "nincada", name: "Ningale", dexNumber: 290, types: ["insecte", "sol"], baseAttack: 18, baseHp: 42, baseCaptureRate: 0.3, rarityWeight: 22, spriteFile: "nincada.png", spriteScale: 0.79, evolution: { intoKey: "ninjask", level: 20 } },
  ninjask: { key: "ninjask", name: "Ninjask", dexNumber: 291, types: ["insecte", "vol"], baseAttack: 26, baseHp: 44, baseCaptureRate: 0.15, rarityWeight: 1, spriteFile: "ninjask.png", spriteScale: 0.84 },
  makuhita: { key: "makuhita", name: "Makuhita", dexNumber: 296, types: ["combat"], baseAttack: 20, baseHp: 50, baseCaptureRate: 0.3, rarityWeight: 22, spriteFile: "makuhita.png", spriteScale: 0.86, evolution: { intoKey: "hariyama", level: 24 } },
  hariyama: { key: "hariyama", name: "Hariyama", dexNumber: 297, types: ["combat"], baseAttack: 26, baseHp: 60, baseCaptureRate: 0.14, rarityWeight: 1, spriteFile: "hariyama.png", spriteScale: 0.97 },
  sableye: { key: "sableye", name: "Ténéfix", dexNumber: 302, types: ["tenebres", "spectre"], baseAttack: 22, baseHp: 48, baseCaptureRate: 0.25, rarityWeight: 16, spriteFile: "sableye.png", spriteScale: 0.79 },
  mawile: { key: "mawile", name: "Mysdibule", dexNumber: 303, types: ["acier", "fee"], baseAttack: 22, baseHp: 44, baseCaptureRate: 0.25, rarityWeight: 18, spriteFile: "mawile.png", spriteScale: 0.81 },
  aron: { key: "aron", name: "Galekid", dexNumber: 304, types: ["acier", "roche"], baseAttack: 20, baseHp: 52, baseCaptureRate: 0.28, rarityWeight: 26, spriteFile: "aron.png", spriteScale: 0.78, evolution: { intoKey: "lairon", level: 32 } },
  lairon: { key: "lairon", name: "Galegon", dexNumber: 305, types: ["acier", "roche"], baseAttack: 25, baseHp: 58, baseCaptureRate: 0.15, rarityWeight: 1, spriteFile: "lairon.png", spriteScale: 0.85, evolution: { intoKey: "aggron", level: 42 } },
  aggron: { key: "aggron", name: "Galeking", dexNumber: 306, types: ["acier", "roche"], baseAttack: 30, baseHp: 66, baseCaptureRate: 0.09, rarityWeight: 1, spriteFile: "aggron.png", spriteScale: 0.95 },
  trapinch: { key: "trapinch", name: "Kraknoix", dexNumber: 328, types: ["sol"], baseAttack: 20, baseHp: 44, baseCaptureRate: 0.3, rarityWeight: 22, spriteFile: "trapinch.png", spriteScale: 0.83, evolution: { intoKey: "vibrava", level: 35 } },
  vibrava: { key: "vibrava", name: "Vibraninf", dexNumber: 329, types: ["sol", "dragon"], baseAttack: 24, baseHp: 48, baseCaptureRate: 0.16, rarityWeight: 1, spriteFile: "vibrava.png", spriteScale: 0.87, evolution: { intoKey: "flygon", level: 45 } },
  flygon: { key: "flygon", name: "Libégon", dexNumber: 330, types: ["sol", "dragon"], baseAttack: 29, baseHp: 56, baseCaptureRate: 0.11, rarityWeight: 1, spriteFile: "flygon.png", spriteScale: 0.95 },
  baltoy: { key: "baltoy", name: "Balbuto", dexNumber: 343, types: ["sol", "psy"], baseAttack: 18, baseHp: 44, baseCaptureRate: 0.32, rarityWeight: 16, spriteFile: "baltoy.png", spriteScale: 0.79, evolution: { intoKey: "claydol", level: 36 } },
  claydol: { key: "claydol", name: "Kaorine", dexNumber: 344, types: ["sol", "psy"], baseAttack: 25, baseHp: 54, baseCaptureRate: 0.14, rarityWeight: 1, spriteFile: "claydol.png", spriteScale: 0.91 },
  bagon: { key: "bagon", name: "Draby", dexNumber: 371, types: ["dragon"], baseAttack: 24, baseHp: 50, baseCaptureRate: 0.15, rarityWeight: 22, spriteFile: "bagon.png", spriteScale: 0.81, evolution: { intoKey: "shelgon", level: 30 } },
  shelgon: { key: "shelgon", name: "Drackhaus", dexNumber: 372, types: ["dragon"], baseAttack: 28, baseHp: 56, baseCaptureRate: 0.1, rarityWeight: 1, spriteFile: "shelgon.png", spriteScale: 0.87, evolution: { intoKey: "salamence", level: 50 } },
  salamence: { key: "salamence", name: "Drattak", dexNumber: 373, types: ["dragon", "vol"], baseAttack: 34, baseHp: 64, baseCaptureRate: 0.06, rarityWeight: 1, spriteFile: "salamence.png", spriteScale: 0.91 },
  beldum: { key: "beldum", name: "Terhal", dexNumber: 374, types: ["acier", "psy"], baseAttack: 22, baseHp: 46, baseCaptureRate: 0.18, rarityWeight: 16, spriteFile: "beldum.png", spriteScale: 0.81, evolution: { intoKey: "metang", level: 20 } },
  metang: { key: "metang", name: "Métang", dexNumber: 375, types: ["acier", "psy"], baseAttack: 26, baseHp: 54, baseCaptureRate: 0.12, rarityWeight: 1, spriteFile: "metang.png", spriteScale: 0.88, evolution: { intoKey: "metagross", level: 45 } },
  metagross: { key: "metagross", name: "Métalosse", dexNumber: 376, types: ["acier", "psy"], baseAttack: 32, baseHp: 62, baseCaptureRate: 0.08, rarityWeight: 1, spriteFile: "metagross.png", spriteScale: 0.92 },
  honchkrow: { key: "honchkrow", name: "Corboss", dexNumber: 430, types: ["tenebres", "vol"], baseAttack: 30, baseHp: 52, baseCaptureRate: 0.11, rarityWeight: 1, spriteFile: "honchkrow.png", spriteScale: 0.85 },
  spiritomb: { key: "spiritomb", name: "Spiritomb", dexNumber: 442, types: ["spectre", "tenebres"], baseAttack: 25, baseHp: 54, baseCaptureRate: 0.12, rarityWeight: 8, spriteFile: "spiritomb.png", spriteScale: 0.86 },
  gible: { key: "gible", name: "Griknot", dexNumber: 443, types: ["dragon", "sol"], baseAttack: 24, baseHp: 50, baseCaptureRate: 0.15, rarityWeight: 20, spriteFile: "gible.png", spriteScale: 0.83, evolution: { intoKey: "gabite", level: 24 } },
  gabite: { key: "gabite", name: "Carmache", dexNumber: 444, types: ["dragon", "sol"], baseAttack: 28, baseHp: 56, baseCaptureRate: 0.1, rarityWeight: 1, spriteFile: "gabite.png", spriteScale: 0.9, evolution: { intoKey: "garchomp", level: 48 } },
  garchomp: { key: "garchomp", name: "Carchacrok", dexNumber: 445, types: ["dragon", "sol"], baseAttack: 34, baseHp: 64, baseCaptureRate: 0.06, rarityWeight: 1, spriteFile: "garchomp.png", spriteScale: 0.94 },
  riolu: { key: "riolu", name: "Riolu", dexNumber: 447, types: ["combat"], baseAttack: 20, baseHp: 40, baseCaptureRate: 0.28, rarityWeight: 14, spriteFile: "riolu.png", spriteScale: 0.83, evolution: { intoKey: "lucario", level: 30 } },
  lucario: { key: "lucario", name: "Lucario", dexNumber: 448, types: ["combat", "acier"], baseAttack: 27, baseHp: 48, baseCaptureRate: 0.12, rarityWeight: 1, spriteFile: "lucario.png", spriteScale: 0.88 },
  croagunk: { key: "croagunk", name: "Cradopaud", dexNumber: 453, types: ["poison", "combat"], baseAttack: 20, baseHp: 44, baseCaptureRate: 0.28, rarityWeight: 18, spriteFile: "croagunk.png", spriteScale: 0.83, evolution: { intoKey: "toxicroak", level: 37 } },
  toxicroak: { key: "toxicroak", name: "Coatox", dexNumber: 454, types: ["poison", "combat"], baseAttack: 26, baseHp: 50, baseCaptureRate: 0.14, rarityWeight: 1, spriteFile: "toxicroak.png", spriteScale: 0.89 },
  weavile: { key: "weavile", name: "Dimoret", dexNumber: 461, types: ["tenebres", "glace"], baseAttack: 31, baseHp: 50, baseCaptureRate: 0.1, rarityWeight: 1, spriteFile: "weavile.png", spriteScale: 0.87 },
  rhyperior: { key: "rhyperior", name: "Rhinastoc", dexNumber: 464, types: ["sol", "roche"], baseAttack: 29, baseHp: 62, baseCaptureRate: 0.1, rarityWeight: 1, spriteFile: "rhyperior.png", spriteScale: 0.97 },
  mamoswine: { key: "mamoswine", name: "Mammochon", dexNumber: 473, types: ["glace", "sol"], baseAttack: 30, baseHp: 62, baseCaptureRate: 0.1, rarityWeight: 1, spriteFile: "mamoswine.png", spriteScale: 0.98 },
  timburr: { key: "timburr", name: "Charpenti", dexNumber: 532, types: ["combat"], baseAttack: 20, baseHp: 46, baseCaptureRate: 0.32, rarityWeight: 18, spriteFile: "timburr.png", spriteScale: 0.81, evolution: { intoKey: "gurdurr", level: 25 } },
  gurdurr: { key: "gurdurr", name: "Ouvrifier", dexNumber: 533, types: ["combat"], baseAttack: 24, baseHp: 52, baseCaptureRate: 0.16, rarityWeight: 1, spriteFile: "gurdurr.png", spriteScale: 0.88, evolution: { intoKey: "conkeldurr", level: 40 } },
  conkeldurr: { key: "conkeldurr", name: "Bétochef", dexNumber: 534, types: ["combat"], baseAttack: 29, baseHp: 58, baseCaptureRate: 0.1, rarityWeight: 1, spriteFile: "conkeldurr.png", spriteScale: 0.9 },
  darumaka: { key: "darumaka", name: "Darumarond", dexNumber: 554, types: ["feu"], baseAttack: 22, baseHp: 42, baseCaptureRate: 0.32, rarityWeight: 22, spriteFile: "darumaka.png", spriteScale: 0.81, evolution: { intoKey: "darmanitan", level: 35 } },
  darmanitan: { key: "darmanitan", name: "Darumacho", dexNumber: 555, types: ["feu"], baseAttack: 27, baseHp: 52, baseCaptureRate: 0.12, rarityWeight: 1, spriteFile: "darmanitan.png", spriteScale: 0.89 },
  scraggy: { key: "scraggy", name: "Baggiguane", dexNumber: 559, types: ["tenebres", "combat"], baseAttack: 22, baseHp: 48, baseCaptureRate: 0.25, rarityWeight: 14, spriteFile: "scraggy.png", spriteScale: 0.81, evolution: { intoKey: "scrafty", level: 39 } },
  scrafty: { key: "scrafty", name: "Baggaïd", dexNumber: 560, types: ["tenebres", "combat"], baseAttack: 28, baseHp: 56, baseCaptureRate: 0.12, rarityWeight: 1, spriteFile: "scrafty.png", spriteScale: 0.87 },
  zorua: { key: "zorua", name: "Zorua", dexNumber: 570, types: ["tenebres"], baseAttack: 24, baseHp: 44, baseCaptureRate: 0.18, rarityWeight: 24, spriteFile: "zorua.png", spriteScale: 0.83, evolution: { intoKey: "zoroark", level: 30 } },
  zoroark: { key: "zoroark", name: "Zoroark", dexNumber: 571, types: ["tenebres"], baseAttack: 30, baseHp: 52, baseCaptureRate: 0.1, rarityWeight: 1, spriteFile: "zoroark.png", spriteScale: 0.92 },
  litwick: { key: "litwick", name: "Funécire", dexNumber: 607, types: ["spectre", "feu"], baseAttack: 18, baseHp: 40, baseCaptureRate: 0.3, rarityWeight: 12, spriteFile: "litwick.png", spriteScale: 0.75, evolution: { intoKey: "lampent", level: 41 } },
  lampent: { key: "lampent", name: "Mélancolux", dexNumber: 608, types: ["spectre", "feu"], baseAttack: 22, baseHp: 46, baseCaptureRate: 0.16, rarityWeight: 1, spriteFile: "lampent.png", spriteScale: 0.81, evolution: { intoKey: "chandelure", level: 50 } },
  chandelure: { key: "chandelure", name: "Lugulabre", dexNumber: 609, types: ["spectre", "feu"], baseAttack: 27, baseHp: 50, baseCaptureRate: 0.1, rarityWeight: 1, spriteFile: "chandelure.png", spriteScale: 0.86 },
  deino: { key: "deino", name: "Solochi", dexNumber: 633, types: ["tenebres", "dragon"], baseAttack: 22, baseHp: 48, baseCaptureRate: 0.12, rarityWeight: 12, spriteFile: "deino.png", spriteScale: 0.84, evolution: { intoKey: "zweilous", level: 50 } },
  zweilous: { key: "zweilous", name: "Diamat", dexNumber: 634, types: ["tenebres", "dragon"], baseAttack: 27, baseHp: 54, baseCaptureRate: 0.09, rarityWeight: 1, spriteFile: "zweilous.png", spriteScale: 0.9, evolution: { intoKey: "hydreigon", level: 64 } },
  hydreigon: { key: "hydreigon", name: "Trioxhydre", dexNumber: 635, types: ["tenebres", "dragon"], baseAttack: 33, baseHp: 62, baseCaptureRate: 0.05, rarityWeight: 1, spriteFile: "hydreigon.png", spriteScale: 0.93 },
};
