-- AlterTable
ALTER TABLE "PlayerState" ADD COLUMN "totalClicks" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "PlayerState" ADD COLUMN "totalPokemonDefeated" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "PlayerState" ADD COLUMN "totalCaptures" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "PlayerState" ADD COLUMN "totalShinyCaptures" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "PlayerState" ADD COLUMN "totalGoldEarned" BIGINT NOT NULL DEFAULT 0;
ALTER TABLE "PlayerState" ADD COLUMN "totalXpEarned" INTEGER NOT NULL DEFAULT 0;
